langchain4j.open-ai.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.temperature=0.2
langchain4j.open-ai.chat-model.timeout=PT400S
langchain4j.open-ai.chat-model.max-tokens=5000
langchain4j.open-ai.chat-model.frequency-penalty=0
langchain4j.open-ai.chat-model.log-requests=false
langchain4j.open-ai.chat-model.log-responses=false
langchain4j.open-ai.chat-model.max-memory-size=50
#
elastic.username=elastic
elastic.password=changeme
elastic.host=localhost
elastic.port=9200

llm-jakarta.documents-dir=${LLM_JAKARTA_DOCUMENTS_DIR}